# -*- coding: utf-8 -*-
# Generated by Django 2.0.1 on 2018-01-17 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(verbose_name='date created')),
                ('start_date', models.DateTimeField(verbose_name='start date and time')),
                ('started', models.BooleanField(default=False)),
                ('num_vms', models.IntegerField(default=100)),
                ('vm_count', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('avg_deployment_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DeploymentMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('value', models.CharField(max_length=256)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployment.Deployment')),
            ],
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('endpoint_url', models.URLField()),
                ('endpoint_type', models.CharField(choices=[('CS', 'CloudStack')], default='CS', max_length=3)),
                ('api_key', models.CharField(max_length=256)),
                ('secret_key', models.CharField(max_length=256)),
                ('created', models.DateTimeField(verbose_name='date created')),
                ('modified', models.DateTimeField(verbose_name='date modified')),
            ],
        ),
        migrations.CreateModel(
            name='EndpointMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('value', models.CharField(max_length=256)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployment.Endpoint')),
            ],
        ),
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
                ('complete', models.BooleanField(default=False)),
                ('async_job', models.CharField(max_length=36)),
                ('deployment_start', models.DateTimeField()),
                ('deployment_finish', models.DateTimeField()),
                ('deployment_duration', models.IntegerField()),
                ('api_request', models.TextField(null=True)),
                ('api_response', models.TextField(null=True)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployment.Deployment')),
            ],
        ),
        migrations.AddField(
            model_name='deployment',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployment.Endpoint'),
        ),
    ]
