# -*- coding: utf-8 -*-
# Generated by Django 2.0.1 on 2018-01-16 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint_MetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('value', models.CharField(max_length=256)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployment.Endpoint')),
            ],
        ),
    ]
