# -*- coding: utf-8 -*-
# Generated by Django 2.0.1 on 2018-01-18 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='deployment',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deployment',
            name='ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='successful',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='events',
            name='deployment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployment.Deployment'),
        ),
        migrations.AddField(
            model_name='events',
            name='virtualmachine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployment.VirtualMachine'),
        ),
    ]
