# -*- coding: utf-8 -*-
# Generated by Django 2.0.1 on 2018-01-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0002_auto_20180118_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='concurrent',
            field=models.IntegerField(default=10),
        ),
    ]
