# -*- coding: utf-8 -*-
# Generated by Django 2.0.1 on 2018-01-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0003_deployment_concurrent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmachine',
            name='deployment_duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='deployment_finish',
            field=models.DateTimeField(null=True),
        ),
    ]
