# -*- coding: utf-8 -*-
# Generated by Django 2.0.1 on 2018-01-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0005_auto_20180119_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='created',
            field=models.DateField(null=True),
        ),
    ]
