# -*- coding: utf-8 -*-
# Generated by Django 2.0.1 on 2018-01-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0006_auto_20180119_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='status_code',
            field=models.IntegerField(null=True),
        ),
    ]
