# -*- coding: utf-8 -*-
# Generated by Django 2.0.1 on 2018-01-19 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0007_events_status_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
